BLOG/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('myblog.urls')),
    path('auth/', include('myauth.urls'))
]

myauth/urls.py
from django.urls import path

from . import views

app_name = "myauth"
urlpatterns = [
    path('login/', views.mylogin, name='login'),
    path('logout/', views.mylogout, name='logout'),
    path('register/', views.register, name='register'),
    path('captcha',views.send_email_captcha,name='email_captcha')
]

myblog/urls.py
from django.urls import path

from . import views

app_name = "myblog"
urlpatterns = [
    path("", views.index, name="index"),
    path("blog/detail/<int:blog_id>/", views.blog_detail, name="blog_detail"),
    path("blog/pub", views.pub_blog, name="pub_blog"),
    path('blog/comment/pub', views.pub_comment, name="pub_comment"),
    path('search', views.search, name="search"),
    path('blog/personalCenter', views.personal_center, name='personal_center'),
    path('blog/aboutUs', views.about_us, name='about_us'),
    path('blog/community', views.community, name='community'),
    path('blog/message', views.message, name='message')
]

templates/about_us.html
{% extends 'base.html' %}
{% block title %}
    关于我们
{% endblock %}
{% block head %}

{% endblock %}
{% block main %}
    <h1>关于我们</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}-BLOG</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
<header class="p-3 text-bg-Light border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/logo.png' %}" alt="logo" width="100" height="45">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="{% url 'myblog:pub_blog' %}" class="nav-link px-2 text-secondary">发布博客</a></li>
                <li><a href="{% url 'myblog:community' %}" class="nav-link px-2 text-secondary">社区</a></li>
                <li><a href="{% url 'myblog:message' %}" class="nav-link px-2 text-secondary">消息</a></li>
                <li><a href="{% url 'myblog:about_us' %}" class="nav-link px-2 text-secondary">关于我们</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'myblog:search' %}"
                  method="get">
                <input type="search" name="q" placeholder="搜索..."
                       aria-label="Search">
            </form>
            {% if user.is_authenticated %}
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle show"
                       data-bs-toggle="dropdown" aria-expanded="true">
                        <img src="{% static 'image/user.png' %}" alt="mdo" width="32" height="32"
                             class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small "
                        style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(0px, 34px, 0px);"
                        data-popper-placement="bottom-start">
                        <li><a class="dropdown-item" href="{% url 'myblog:personal_center' %}">个人中心</a></li>
                        <li><a class="dropdown-item" href="#">内容管理</a></li>
                        <li><a class="dropdown-item" href="#">相关设置</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'myauth:logout' %}">退出登录</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="text-end">
                    <a href="{% url 'myauth:login' %}" type="button" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'myauth:register' %}" type="button" class="btn btn-primary">注册</a>
                </div>
            {% endif %}
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded">
    {% block main %}{% endblock %}
</main>
</body>
</html>

templates/blog_detail.html
{% extends 'base.html' %}

{% block title %}
    博客详情
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'highlight/styles/github-dark.min.css' %}">
    <script src="{% static 'highlight/highlight.min.js' %}"></script>
{% endblock %}

{% block main %}
    <h1>{{ blog.title }}</h1>
    <hr>
    <div class="mt-2">
        <img src="{% static 'image/user.png' %}" class="rounded-circle" width="30" height="30">
        <span class="ms-2">{{ blog.author.username }}</span>
        <span class="ms-2">于</span>
        <span class="ms-2">{{ blog.pub_time|date:'Y年m月d日 H时:i分:s秒' }}</span>发布
    </div>
    <hr>
    <div class="py-2">
        {{ blog.content|safe }}
    </div>
    <hr>
    <div class="mt-2">
        <h3>评论({{ blog.comments.all|length }})</h3>
        <form action="{% url 'myblog:pub_comment' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="blog_id" value="{{ blog.id }}">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="请输入评论内容" name="content">
            </div>
            <div class="text-end mt-2">
                <button type="button" class="btn btn-primary">评论</button>
            </div>
        </form>
    </div>
    <div class="mt-2">
        <ul class="list-group list-group-flush">
            {% for comment in blog.comments.all %}
                <li class="list-group-item mb-3">
                    <div class="d-flex justify-content-between text-body-secondary">
                        <div class="user-info ">
                            <img src="{% static 'image/user.png' %}" class="rounded-circle" width="40" height="40">
                            <span class="ms-2">{{ comment.author.username }}</span>
                        </div>
                        <div class="create-time"
                             style="line-height: 40px;">{{ comment.pub_time|date:'Y年m月d日 H时:i分:s秒' }}</div>
                    </div>
                    <div class="mt-2">{{ comment.content }}</div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <script>
        hljs.highlightAll();
    </script>
{% endblock %}

templates/community.html
{% extends 'base.html' %}
{% block title %}
    社区
{% endblock %}
{% block head %}

{% endblock %}
{% block main %}
    <h1>社区</h1>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
    博客首页
{% endblock %}

{% block main %}
    <h1>博客列表</h1>
    <div class="row row-cols-2 row-gap-4">
        {% for blog in blogs %}
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <a href="{% url 'myblog:blog_detail' blog_id=blog.id %}" class="card-link">{{ blog.title }}</a>
                    </div>
                    <div class="card-body" style="height: 100px">
                        <p class="card-text">{{ blog.content|striptags|truncatechars:200 }}</p>
                    </div>
                    <div class="card-footer text-body-secondary d-flex justify-content-between">
                        <div>
                            <img src="{% static 'image/user.png' %}" class="rounded-circle" width="30" height="30">
                            {{ blog.author.username }}
                        </div>
                        <div>
                            {{ blog.pub_time|date:'Y年m月d日 H时:i分:s秒' }}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}
    登录
{% endblock %}

{% block main %}
    <div style="max-width: 330px;" class="m-auto">
        <h1>登录</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>
            <div class="form-check form-switch mb-3">
                <input class="form-check-input" type="checkbox" role="switch" name="remember" value="1"
                       id="flexSwitchCheckChecked" checked>
                <label class="form-check-label" for="flexSwitchCheckChecked">记住密码</label>
            </div>
            <div class="mb-3 text-xl-center">
                <button class="btn btn-primary w-100">立即登录</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/message.html
{% extends 'base.html' %}
{% block title %}
    消息
{% endblock %}
{% block head %}

{% endblock %}
{% block main %}
    <h1>消息</h1>
{% endblock %}

templates/personal_center.html
{% extends 'base.html' %}
{% block title %}
    个人中心
{% endblock %}
{% block head %}

{% endblock %}
{% block main %}
    <h1>个人中心</h1>
{% endblock %}

templates/pub_blog.html
{% extends 'base.html' %}

{% block title %}
    发布博客
{% endblock %}

{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'wangeditor/style.css' %}">
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <script src="{% static 'js/pub_blog.js' %}"></script>
    <style>
        #editor—wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* 按需定义 */
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px;
        }
    </style>
{% endblock %}

{% block main %}
    <h1>发布博客</h1>
    <div class="mt-3">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label class="form-label">标题</label>
                <input type="text" name="title" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">分类</label>
                <select name="category" class="form-select" id="category-select">
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}

                </select>
            </div>
            <div class="mb-3">
                <label class="form-label">内容</label>
                <div id="editor—wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
            <div class="mb-3 text-end">
                <button type="submit" class="btn btn-primary" id="pub-blog-btn">发布</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}
    注册
{% endblock %}

{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}

{% block main %}
    <div style="max-width: 330px;" class="m-auto">
        <h1>注册</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label>用户名</label>
                <input type="text" name="username" class="form-control" placeholder="用户名">
            </div>
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label>验证码</label>
                <div class="input-group mb-3">
                    <input type="text" name="captcha" class="form-control" placeholder="验证码"
                           aria-label="Recipient's username" aria-describedby="button-addon2">
                    <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                </div>
            </div>
            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>

            <div class="mb-3 text-xl-center">
                <button class="btn btn-primary w-100">注册</button>
            </div>
        </form>
    </div>
{% endblock %}